name: deploy-to-rhel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - linux
      - x64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Python Environment
        run: |
          python3 -m pip install --upgrade pip
          pip install ruff

      - name: Linting
        run: |
          ruff check .
          ruff format .

      - name: Deploy App
        run: |
          echo "Stopping old containers..."
          docker stop my-python-app || true
          docker rm my-python-app || true

          echo "Building image..."
          docker build -t simple-python-app:latest -f docker/Dockerfile ./

          echo "Starting container..."
          docker run -d \
            --name my-python-app \
            -p 8080:8080 \
            simple-python-app:latest

      - name: Terraform OCI
        run: |
          cd /home/github/terraform
          terraform init
          terraform apply -auto-approve

      - name: Ansible
        run: |
          cd /home/github/ansible
          ansible-playbook deploy.yml
